#!/bin/bash

echo "|-----------------------------------------------------------------------------|"
echo "|                                     TESTS                                   |"
echo "|-----------------------------------------------------------------------------|"
echo ""
echo "|-----------------------------------------------------------------------------|"
echo "|              Test de l'API pour accéder à la page d'accueil                 |"
echo "|-----------------------------------------------------------------------------|"
echo "Requête exécutée :"
echo """curl -kiL -X GET https://redthreadapi.drv.p2021.ajoga.fr/"""
read -n 1 -r -s -p $'Appuyez sur Entrée pour continuer\n'
curl -kiL -X GET https://redthreadapi.drv.p2021.ajoga.fr/
echo ""
echo "|-----------------------------------------------------------------------------|"
echo "|                   Test de l'API en envoyant un fichier PNG                  |"
echo "|-----------------------------------------------------------------------------|"
echo "Requête exécutée :"
echo """curl -kiL -X POST -u lambda:@ReTh20@ https://redthreadapi.drv.p2021.ajoga.fr/upload -F 'file=@test_files/test.png'"""
read -n 1 -r -s -p $'Appuyez sur Entrée pour continuer\n'
curl -kiL -X POST -u lambda:@ReTh20@ https://redthreadapi.drv.p2021.ajoga.fr/upload -F "file=@test_files/test.png"
echo ""
echo "|-----------------------------------------------------------------------------|"
echo "|                   Test de l'API en envoyant un fichier JPG                  |"
echo "|-----------------------------------------------------------------------------|"
echo "Requête exécutée :"
echo """curl -kiL -X POST -u lambda:@ReTh20@ https://redthreadapi.drv.p2021.ajoga.fr/upload -F 'file=@test_files/test.jpg'"""
read -n 1 -r -s -p $'Appuyez sur Entrée pour continuer\n'
curl -kiL -X POST -u lambda:@ReTh20@ https://redthreadapi.drv.p2021.ajoga.fr/upload -F "file=@test_files/test.jpg"
echo ""
echo "|-----------------------------------------------------------------------------|"
echo "|                   Test de l'API en envoyant un fichier BMP                  |"
echo "|-----------------------------------------------------------------------------|"
echo "Requête exécutée :"
echo """curl -kiL -X POST -u lambda:@ReTh20@ https://redthreadapi.drv.p2021.ajoga.fr/upload -F 'file=@test_files/test.bmp'"""
read -n 1 -r -s -p $'Appuyez sur Entrée pour continuer\n'
curl -kiL -X POST -u lambda:@ReTh20@ https://redthreadapi.drv.p2021.ajoga.fr/upload -F "file=@test_files/test.bmp"
echo ""
echo "|-----------------------------------------------------------------------------|"
echo "|                   Test de l'API en envoyant un fichier GIF                  |"
echo "|-----------------------------------------------------------------------------|"
echo "Requête exécutée :"
echo """curl -kiL -X POST -u lambda:@ReTh20@ https://redthreadapi.drv.p2021.ajoga.fr/upload -F 'file=@test_files/test.gif'"""
read -n 1 -r -s -p $'Appuyez sur Entrée pour continuer\n'
curl -kiL -X POST -u lambda:@ReTh20@ https://redthreadapi.drv.p2021.ajoga.fr/upload -F "file=@test_files/test.gif"
echo ""
echo "|------------------------------------------------------------------------------|"
echo "|                   Test de l'API en envoyant un fichier CSV                   |"
echo "|------------------------------------------------------------------------------|"
echo "Requête exécutée :"
echo """curl -kiL -X POST -u lambda:@ReTh20@ https://redthreadapi.drv.p2021.ajoga.fr/upload -F 'file=@test_files/test.csv'"""
read -n 1 -r -s -p $'Appuyez sur Entrée pour continuer\n'
curl -kiL -X POST -u lambda:@ReTh20@ https://redthreadapi.drv.p2021.ajoga.fr/upload -F "file=@test_files/test.csv"
echo ""
echo "|------------------------------------------------------------------------------|"
echo "|                   Test de l'API en envoyant un fichier TXT                   |"
echo "|------------------------------------------------------------------------------|"
echo "Requête exécutée :"
echo """curl -kiL -X POST -u lambda:@ReTh20@ https://redthreadapi.drv.p2021.ajoga.fr/upload -F 'file=@test_files/test.txt'"""
read -n 1 -r -s -p $'Appuyez sur Entrée pour continuer\n'
curl -kiL -X POST -u lambda:@ReTh20@ https://redthreadapi.drv.p2021.ajoga.fr/upload -F "file=@test_files/test.txt"
echo ""
echo "|------------------------------------------------------------------------------|"
echo "|                   Test de l'API en envoyant un fichier DOCX                  |"
echo "|------------------------------------------------------------------------------|"
echo "Requête exécutée :"
echo "curl -kiL -X POST -u lambda:@ReTh20@ https://redthreadapi.drv.p2021.ajoga.fr/upload -F 'file=@test_files/test.docx'"""
read -n 1 -r -s -p $'Appuyez sur Entrée pour continuer\n'
curl -kiL -X POST -u lambda:@ReTh20@ https://redthreadapi.drv.p2021.ajoga.fr/upload -F "file=@test_files/test.docx"
echo ""
echo "|------------------------------------------------------------------------------|"
echo "|                   Test de l'API en envoyant un fichier PDF                   |"
echo "|------------------------------------------------------------------------------|"
echo "Requête exécutée :"
echo """curl -kiL -X POST -u lambda:@ReTh20@ https://redthreadapi.drv.p2021.ajoga.fr/upload -F 'file=@test_files/test.pdf'"""
read -n 1 -r -s -p $'Appuyez sur Entrée pour continuer\n'
curl -kiL -X POST -u lambda:@ReTh20@ https://redthreadapi.drv.p2021.ajoga.fr/upload -F "file=@test_files/test.pdf"
echo ""
echo "|------------------------------------------------------------------------------|"
echo "|                   Test de l'API en envoyant un fichier MP3                   |"
echo "|------------------------------------------------------------------------------|"
echo "Requête exécutée :"
echo """curl -kiL -X POST -u lambda:@ReTh20@ https://redthreadapi.drv.p2021.ajoga.fr/upload -F 'file=@test_files/test.mp3'"""
read -n 1 -r -s -p $'Appuyez sur Entrée pour continuer\n'
curl -kiL -X POST -u lambda:@ReTh20@ https://redthreadapi.drv.p2021.ajoga.fr/upload -F "file=@test_files/test.mp3"
echo ""
echo "|------------------------------------------------------------------------------|"
echo "|                   Test de l'API en envoyant un fichier M4A                   |"
echo "|------------------------------------------------------------------------------|"
echo "Requête exécutée :"
echo """curl -kiL -X POST -u lambda:@ReTh20@ https://redthreadapi.drv.p2021.ajoga.fr/upload -F 'file=@test_files/test.m4a'"""
read -n 1 -r -s -p $'Appuyez sur Entrée pour continuer\n'
curl -kiL -X POST -u lambda:@ReTh20@ https://redthreadapi.drv.p2021.ajoga.fr/upload -F "file=@test_files/test.m4a"
echo ""
echo "|------------------------------------------------------------------------------|"
echo "|                   Test de l'API en envoyant un fichier FLAC                  |"
echo "|------------------------------------------------------------------------------|"
echo "Requête exécutée :"
echo """curl -kiL -X POST -u lambda:@ReTh20@ https://redthreadapi.drv.p2021.ajoga.fr/upload -F 'file=@test_files/test.flac'"""
read -n 1 -r -s -p $'Appuyez sur Entrée pour continuer\n'
curl -kiL -X POST -u lambda:@ReTh20@ https://redthreadapi.drv.p2021.ajoga.fr/upload -F "file=@test_files/test.flac"
echo ""
echo "|------------------------------------------------------------------------------|"
echo "|                   Test de l'API en envoyant un fichier OGG                   |"
echo "|------------------------------------------------------------------------------|"
echo "Requête exécutée :"
echo """curl -kiL -X POST -u lambda:@ReTh20@ https://redthreadapi.drv.p2021.ajoga.fr/upload -F 'file=@test_files/test.ogg'"""
read -n 1 -r -s -p $'Appuyez sur Entrée pour continuer\n'
curl -kiL -X POST -u lambda:@ReTh20@ https://redthreadapi.drv.p2021.ajoga.fr/upload -F "file=@test_files/test.ogg"
echo ""
echo "|------------------------------------------------------------------------------|"
echo "|                   Test de l'API en envoyant un fichier OPUS                  |"
echo "|------------------------------------------------------------------------------|"
echo "Requête exécutée :"
echo """curl -kiL -X POST -u lambda:@ReTh20@ https://redthreadapi.drv.p2021.ajoga.fr/upload -F 'file=@test_files/test.opus'"""
read -n 1 -r -s -p $'Appuyez sur Entrée pour continuer\n'
curl -kiL -X POST -u lambda:@ReTh20@ https://redthreadapi.drv.p2021.ajoga.fr/upload -F "file=@test_files/test.opus"
echo ""
echo "|------------------------------------------------------------------------------|"
echo "|                   Test de l'API en envoyant un fichier WAV                   |"
echo "|------------------------------------------------------------------------------|"
echo "Requête exécutée :"
echo """curl -kiL -X POST -u lambda:@ReTh20@ https://redthreadapi.drv.p2021.ajoga.fr/upload -F 'file=@test_files/test.wav'"""
read -n 1 -r -s -p $'Appuyez sur Entrée pour continuer\n'
curl -kiL -X POST -u lambda:@ReTh20@ https://redthreadapi.drv.p2021.ajoga.fr/upload -F "file=@test_files/test.wav"
echo ""
echo "|------------------------------------------------------------------------------|"
echo "|                   Test de l'API en envoyant un fichier WMA                   |"
echo "|------------------------------------------------------------------------------|"
echo "Requête exécutée :"
echo """curl -kiL -X POST -u lambda:@ReTh20@ https://redthreadapi.drv.p2021.ajoga.fr/upload -F 'file=@test_files/test.wma'"""
read -n 1 -r -s -p $'Appuyez sur Entrée pour continuer\n'
curl -kiL -X POST -u lambda:@ReTh20@ https://redthreadapi.drv.p2021.ajoga.fr/upload -F "file=@test_files/test.wma"
echo ""
echo "|------------------------------------------------------------------------------|"
echo "|  Test de l'API en envoyant un fichier avec une extension non prise en charge |"
echo "|------------------------------------------------------------------------------|"
echo "Requête exécutée :"
echo """curl -kiL -X POST -u lambda:@ReTh20@ https://redthreadapi.drv.p2021.ajoga.fr/upload -F 'file=@test_files/test.py'"""
read -n 1 -r -s -p $'Appuyez sur Entrée pour continuer\n'
curl -kiL -X POST -u lambda:@ReTh20@ https://redthreadapi.drv.p2021.ajoga.fr/upload -F "file=@test_files/test.py"
echo ""
echo "|------------------------------------------------------------------------------|"
echo "|    Test de l'API en envoyant un fichier dans un format non pris en charge    |"
echo "|------------------------------------------------------------------------------|"
echo "Requête exécutée :"
echo """curl -kiL -X POST -u lambda:@ReTh20@ https://redthreadapi.drv.p2021.ajoga.fr/upload -F 'file=@test_files/testpy.jpg'"""
read -n 1 -r -s -p $'Appuyez sur Entrée pour continuer\n'
curl -kiL -X POST -u lambda:@ReTh20@ https://redthreadapi.drv.p2021.ajoga.fr/upload -F "file=@test_files/testpy.jpg"
echo ""
echo "|------------------------------------------------------------------------------|"
echo "|             Test de l'API en envoyant un fichier trop volumineux             |"
echo "|------------------------------------------------------------------------------|"
echo "Requête exécutée :"
echo """curl -kiL -X POST -u lambda:@ReTh20@ https://redthreadapi.drv.p2021.ajoga.fr/upload -F 'file=@test_files/test.mov'"""
read -n 1 -r -s -p $'Appuyez sur Entrée pour continuer\n'
curl -kiL -X POST -u lambda:@ReTh20@ https://redthreadapi.drv.p2021.ajoga.fr/upload -F "file=@test_files/test.mov"
echo ""
echo "|------------------------------------------------------------------------------|"
echo "|                   Test de l'API sans authentification                        |"
echo "|------------------------------------------------------------------------------|"
echo "Requête exécutée :"
echo """curl -kiL -X POST https://redthreadapi.drv.p2021.ajoga.fr/upload -F 'file=@test_files/test.txt'"""
read -n 1 -r -s -p $'Appuyez sur Entrée pour continuer\n'
curl -kiL -X POST https://redthreadapi.drv.p2021.ajoga.fr/upload -F "file=@test_files/test.txt"
echo ""
echo "|------------------------------------------------------------------------------|"
echo "|                    Test de l'API avec un login inconnu                       |"
echo "|------------------------------------------------------------------------------|"
echo "Requête exécutée :"
echo """curl -kiL -X POST -u WrongLogin:@ReTh20@ https://redthreadapi.drv.p2021.ajoga.fr/upload -F 'file=@test_files/test.txt'"""
read -n 1 -r -s -p $'Appuyez sur Entrée pour continuer\n'
curl -kiL -X POST -u WrongLogin:@ReTh20@ https://redthreadapi.drv.p2021.ajoga.fr/upload -F "file=@test_files/test.txt"
echo ""
echo "|------------------------------------------------------------------------------|"
echo "|                 Test de l'API avec un mot de passe invalide                  |"
echo "|------------------------------------------------------------------------------|"
echo "Requête exécutée :"
echo """curl -kiL -X POST -u lambda:WrongPassword https://redthreadapi.drv.p2021.ajoga.fr/upload -F 'file=@test_files/test.txt'"""
read -n 1 -r -s -p $'Appuyez sur Entrée pour continuer\n'
curl -kiL -X POST -u lambda:WrongPassword https://redthreadapi.drv.p2021.ajoga.fr/upload -F "file=@test_files/test.txt"
echo ""
echo "|------------------------------------------------------------------------------|"
echo "|                  Test de l'API en faisant une requête http                   |"
echo "|------------------------------------------------------------------------------|"
echo "Requête exécutée :"
echo """curl -kiL -X POST -u lambda:@ReTh20@ http://redthreadapi.drv.p2021.ajoga.fr/upload -F 'file=@test_files/test.txt'"""
read -n 1 -r -s -p $'Appuyez sur Entrée pour continuer\n'
curl -kiL -X POST -u lambda:@ReTh20@ http://redthreadapi.drv.p2021.ajoga.fr/upload -F "file=@test_files/test.txt"
echo ""
echo "|------------------------------------------------------------------------------|"
echo "|            Test de l'API pour lister les fichiers dans le bucket             |"
echo "|------------------------------------------------------------------------------|"
echo "Requête exécutée :"
echo """curl -kiL -X GET -u lambda:@ReTh20@ https://redthreadapi.drv.p2021.ajoga.fr/list_files"""
read -n 1 -r -s -p $'Appuyez sur Entrée pour continuer\n'
curl -kiL -X GET -u lambda:@ReTh20@ https://redthreadapi.drv.p2021.ajoga.fr/list_files
echo ""
echo "|------------------------------------------------------------------------------|"
echo "|          Test de l'API pour télécharger un fichier depuis le bucket          |"
echo "|------------------------------------------------------------------------------|"
echo "Requête exécutée :"
echo """curl -kiL -X GET -u lambda:@ReTh20@ https://redthreadapi.drv.p2021.ajoga.fr/download/<filename>"""
read -n 1 -r -s -p $'Appuyez sur Entrée pour continuer\n'
var=$(curl -kiL -X GET -u lambda:@ReTh20@ https://redthreadapi.drv.p2021.ajoga.fr/list_files | tail -n 1 | tr "\"" "\n" | grep txt | sed -n 1p)
curl -kiL -X GET -u lambda:@ReTh20@ https://redthreadapi.drv.p2021.ajoga.fr/download/$var
echo ""
echo "|------------------------------------------------------------------------------|"
echo "|            Test de l'API pour effacer tous les fichiers du bucket            |"
echo "|                   (seul l'administrateur peut normalement)                   |"
echo "|------------------------------------------------------------------------------|"
echo ""
echo "           Pour cette requête, munissez-vous de votre mot de passe."
echo "       J'ai fait en sorte que vous puissiez effectuer cette étape avec." 
echo ""
echo "Requête exécutée :"
echo """curl -kiL -X DELETE -u francois.laissus https://redthreadapi.drv.p2021.ajoga.fr/empty_bucket"""
read -n 1 -r -s -p $'Appuyez sur Entrée pour continuer\n'
curl -kiL -X DELETE -u francois.laissus https://redthreadapi.drv.p2021.ajoga.fr/empty_bucket
echo ""
echo "|------------------------------------------------------------------------------|"
echo "|            Test de l'API pour vérifier que le bucket bien vide               |"
echo "|------------------------------------------------------------------------------|"
echo "Requête exécutée :"
echo """curl -kiL -X GET -u lambda:@ReTh20@ https://redthreadapi.drv.p2021.ajoga.fr/list_files"""
read -n 1 -r -s -p $'Appuyez sur Entrée pour continuer\n'
curl -kiL -X GET -u lambda:@ReTh20@ https://redthreadapi.drv.p2021.ajoga.fr/list_files
