#!/bin/bash

echo "|-----------------------------------------------------------------------------|"
echo "|                                     TESTS                                   |"
echo "|-----------------------------------------------------------------------------|"
echo ""
echo "|-----------------------------------------------------------------------------|"
echo "|                   Test de l'API en envoyant un fichier PNG                  |"
echo "|-----------------------------------------------------------------------------|"
echo """Requête exécutée : curl -kiL -X POST -u lambda:0000 https://redthreadapi.drv.p2021.ajoga.fr/upload_file -F 'file=@test_files/test.png'"""
read -n 1 -r -s -p $'Appuyez sur une touche pour continuer\n'
curl -kiL -X POST -u lambda:0000 https://redthreadapi.drv.p2021.ajoga.fr/upload_file -F "file=@test_files/test.png"
echo ""
echo "|-----------------------------------------------------------------------------|"
echo "|                   Test de l'API en envoyant un fichier JPG                  |"
echo "|-----------------------------------------------------------------------------|"
echo """Requête exécutée : curl -kiL -X POST -u lambda:0000 https://redthreadapi.drv.p2021.ajoga.fr/upload_file -F 'file=@test_files/test.jpg'"""
curl -kiL -X POST -u lambda:0000 https://redthreadapi.drv.p2021.ajoga.fr/upload_file -F "file=@test_files/test.jpg"
echo ""
echo "|-----------------------------------------------------------------------------|"
echo "|                   Test de l'API en envoyant un fichier BMP                  |"
echo "|-----------------------------------------------------------------------------|"
echo """Requête exécutée : curl -kiL -X POST -u lambda:0000 https://redthreadapi.drv.p2021.ajoga.fr/upload_file -F 'file=@test_files/test.bmp'"""
read -n 1 -r -s -p $'Appuyez sur une touche pour continuer\n'
curl -kiL -X POST -u lambda:0000 https://redthreadapi.drv.p2021.ajoga.fr/upload_file -F "file=@test_files/test.bmp"
echo ""
echo "|-----------------------------------------------------------------------------|"
echo "|                   Test de l'API en envoyant un fichier GIF                  |"
echo "|-----------------------------------------------------------------------------|"
echo """Requête exécutée : curl -kiL -X POST -u lambda:0000 https://redthreadapi.drv.p2021.ajoga.fr/upload_file -F 'file=@test_files/test.gif'"""
read -n 1 -r -s -p $'Appuyez sur une touche pour continuer\n'
curl -kiL -X POST -u lambda:0000 https://redthreadapi.drv.p2021.ajoga.fr/upload_file -F "file=@test_files/test.gif"
echo ""
echo "|------------------------------------------------------------------------------|"
echo "|                   Test de l'API en envoyant un fichier CSV                   |"
echo "|------------------------------------------------------------------------------|"
echo """Requête exécutée : curl -kiL -X POST -u lambda:0000 https://redthreadapi.drv.p2021.ajoga.fr/upload_file -F 'file=@test_files/test.csv'"""
read -n 1 -r -s -p $'Appuyez sur une touche pour continuer\n'
curl -kiL -X POST -u lambda:0000 https://redthreadapi.drv.p2021.ajoga.fr/upload_file -F "file=@test_files/test.csv"
echo ""
echo "|------------------------------------------------------------------------------|"
echo "|                   Test de l'API en envoyant un fichier TXT                   |"
echo "|------------------------------------------------------------------------------|"
echo """Requête exécutée : curl -kiL -X POST -u lambda:0000 https://redthreadapi.drv.p2021.ajoga.fr/upload_file -F 'file=@test_files/test.txt'"""
read -n 1 -r -s -p $'Appuyez sur une touche pour continuer\n'
curl -kiL -X POST -u lambda:0000 https://redthreadapi.drv.p2021.ajoga.fr/upload_file -F "file=@test_files/test.txt"
echo ""
echo "|------------------------------------------------------------------------------|"
echo "|                   Test de l'API en envoyant un fichier DOCX                  |"
echo "|------------------------------------------------------------------------------|"
echo """Requête exécutée : curl -kiL -X POST -u lambda:0000 https://redthreadapi.drv.p2021.ajoga.fr/upload_file -F 'file=@test_files/test.docx'"""
read -n 1 -r -s -p $'Appuyez sur une touche pour continuer\n'
curl -kiL -X POST -u lambda:0000 https://redthreadapi.drv.p2021.ajoga.fr/upload_file -F "file=@test_files/test.docx"
echo ""
echo "|------------------------------------------------------------------------------|"
echo "|                   Test de l'API en envoyant un fichier PDF                   |"
echo "|------------------------------------------------------------------------------|"
echo """Requête exécutée : curl -kiL -X POST -u lambda:0000 https://redthreadapi.drv.p2021.ajoga.fr/upload_file -F 'file=@test_files/test.pdf'"""
read -n 1 -r -s -p $'Appuyez sur une touche pour continuer\n'
curl -kiL -X POST -u lambda:0000 https://redthreadapi.drv.p2021.ajoga.fr/upload_file -F "file=@test_files/test.pdf"
echo ""
echo "|------------------------------------------------------------------------------|"
echo "|  Test de l'API en envoyant un fichier avec une extension non prise en charge |"
echo "|------------------------------------------------------------------------------|"
echo """Requête exécutée : curl -kiL -X POST -u lambda:0000 https://redthreadapi.drv.p2021.ajoga.fr/upload_file -F 'file=@test_files/test.py'"""
read -n 1 -r -s -p $'Appuyez sur une touche pour continuer\n'
curl -kiL -X POST -u lambda:0000 https://redthreadapi.drv.p2021.ajoga.fr/upload_file -F "file=@test_files/test.py"
echo ""
echo "|------------------------------------------------------------------------------|"
echo "|    Test de l'API en envoyant un fichier dans un format non pris en charge    |"
echo "|------------------------------------------------------------------------------|"
echo """Requête exécutée : curl -kiL -X POST -u lambda:0000 https://redthreadapi.drv.p2021.ajoga.fr/upload_file -F 'file=@test_files/testpy.jpg'"""
read -n 1 -r -s -p $'Appuyez sur une touche pour continuer\n'
curl -kiL -X POST -u lambda:0000 https://redthreadapi.drv.p2021.ajoga.fr/upload_file -F "file=@test_files/testpy.jpg"
echo ""
echo "|------------------------------------------------------------------------------|"
echo "|             Test de l'API en envoyant un fichier trop volumineux             |"
echo "|------------------------------------------------------------------------------|"
echo """Requête exécutée : curl -kiL -X POST -u lambda:0000 https://redthreadapi.drv.p2021.ajoga.fr/upload_file -F 'file=@test_files/test.mov'"""
read -n 1 -r -s -p $'Appuyez sur une touche pour continuer\n'
curl -kiL -X POST -u lambda:0000 https://redthreadapi.drv.p2021.ajoga.fr/upload_file -F "file=@test_files/test.mov"
echo ""
echo "|------------------------------------------------------------------------------|"
echo "|                   Test de l'API sans authentification                        |"
echo "|------------------------------------------------------------------------------|"
echo """Requête exécutée : curl -kiL -X POST https://redthreadapi.drv.p2021.ajoga.fr/upload_file -F 'file=@test_files/test.txt'"""
read -n 1 -r -s -p $'Appuyez sur une touche pour continuer\n'
curl -kiL -X POST https://redthreadapi.drv.p2021.ajoga.fr/upload_file -F "file=@test_files/test.txt"
echo ""
echo "|------------------------------------------------------------------------------|"
echo "|                    Test de l'API avec un login inconnu                       |"
echo "|------------------------------------------------------------------------------|"
echo """Requête exécutée : curl -kiL -X POST -u WrongLogin:0000 https://redthreadapi.drv.p2021.ajoga.fr/upload_file -F 'file=@test_files/test.txt'"""
read -n 1 -r -s -p $'Appuyez sur une touche pour continuer\n'
curl -kiL -X POST -u WrongLogin:0000 https://redthreadapi.drv.p2021.ajoga.fr/upload_file -F "file=@test_files/test.txt"
echo ""
echo "|------------------------------------------------------------------------------|"
echo "|                 Test de l'API avec un mot de passe invalide                  |"
echo "|------------------------------------------------------------------------------|"
echo """Requête exécutée : curl -kiL -X POST -u lambda:WrongPassword https://redthreadapi.drv.p2021.ajoga.fr/upload_file -F 'file=@test_files/test.txt'"""
read -n 1 -r -s -p $'Appuyez sur une touche pour continuer\n'
curl -kiL -X POST -u lambda:WrongPassword https://redthreadapi.drv.p2021.ajoga.fr/upload_file -F "file=@test_files/test.txt"
echo ""
echo "|------------------------------------------------------------------------------|"
echo "|                  Test de l'API en faisant une requête http                   |"
echo "|------------------------------------------------------------------------------|"
echo """Requête exécutée : curl -kiL -X POST -u lambda:0000 http://redthreadapi.drv.p2021.ajoga.fr/upload_file -F 'file=@test_files/test.txt'"""
read -n 1 -r -s -p $'Appuyez sur une touche pour continuer\n'
curl -kiL -X POST -u lambda:0000 http://redthreadapi.drv.p2021.ajoga.fr/upload_file -F "file=@test_files/test.txt"

